site_name: sample-app-rhdh
site_description: 
repo_url: https://github.com/piomin/sample-app-rhdh
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - sample-app-rhdh Documentation: index.md